
#Makefile for program hello
 
program := timer
 
sources := $(wildcard src/*.c)
headers := $(wildcard *.h)
 
objects := $(sources:.c=.o)
deps    := $(sources:.c=.d)
 
CC      := g++
SHARED  := -shared
FPIC    := -fPIC
CFLAGS  := -g -Wall -Werror -pthread -I./include
LDFLAGS := 
 
RM      := rm -f

me      := Makefile
 
all:    $(program)
 
timer:  $(objects)
		$(CC) -o $@ $(CFLAGS) $(objects) $(LDFLAGS) $(LDLIBS)

clean:
		$(RM) $(objects)
		$(RM) $(deps)
		$(RM) $(program)

-include $(deps)
